FROM alpine:3.13

RUN apk add --no-cache kea-dhcp4 kea-admin mariadb-client postgresql-client jq \
    && mkdir -p /run/kea

COPY scripts/start.sh /etc/kea/start.sh

RUN chmod +x /etc/kea/start.sh

ENTRYPOINT [ "/bin/sh" ]

CMD [ "-e", "/etc/kea/start.sh" ]
