version: '3'
services:
  kea-dhcp4:
    image: winglim/kea-dhcp4
    volumes:
      - '$PWD/conf/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf'
      - '$PWD/conf/dhcp4.leases:/var/lib/kea/dhcp4.leases'
    restart: always
    network_mode: host
    container_name: kea-dhcp4
  
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_DATABASE=keadhcp4
      - MYSQL_USER=keauser
      - MYSQL_PASSWORD=keapassword
    volumes:
      - '$PWD/conf/db:/config'
    restart: always
    container_name: kea-mariadb
