FROM alpine:edge

RUN apk add --no-cache kea-dhcp4 kea-admin mariadb-client jq \
    && mkdir -p /run/kea

COPY scripts/start.sh /etc/kea/start.sh

# fix kea-admin scripts path
RUN if [ -d /usr/share/kea/kea/ ];then \
    mv /usr/share/kea/kea/* /usr/share/kea/ \
    && rm -r /usr/share/kea/kea/; \
fi

RUN chmod +x /etc/kea/start.sh

ENTRYPOINT [ "/bin/sh" ]

CMD [ "-e", "/etc/kea/start.sh" ]
